### ISSUE TITLE
Project plan - Technical Improvements

### ISSUE THREAD

**Issue by theodorosploumis** [theodorosploumis/drupal-docker-distros#2]
1. Add Screenshots for each distribution on the select list.
1. SSH to docker images from external IPs.
1. Immediately login Admin after 1st redirect (provide a 1 time login url)
1. Open new Instance on a new browser tab. 
1. Create [Portainer templates](https://portainer.readthedocs.io/en/stable/templates.html) for each distro
1. Change nginx default text for 503 error (link to main domain)
1. Add patches from the UI form
1. Use custom subdomain per user
1. Create Main Site and Agent (docker containers on port 80 and nginx-proxy) with **short url**.
1. Create volumes? (`mkdir /var/www/$ID`)
1. Use linked containers (mysql, server) from base images with --volumes-from
1. Create an Ansible stack for server provisioning
1. Use Makefile to build distros and push on docker hub from travis
1. Include error reporting on settings.php by default (See https://www.drupal.org/node/158043)
1. Stats for Distros used
1. Use [xtermjs](https://xtermjs.org) for the **terminal**.
1. [x] Add on Drupal.org General Projects: https://www.drupal.org/project/project_general
1. [x] Login to use the site (maybe using a social network) or use a Captcha1. [x] Include 7.x distributions
1. [x] Create a custom Base image
1. [x] Use [Let's Encrypt](https://letsencrypt.org/) for main domain
1. [x] Add a time limit to kill containers
