### ISSUE TITLE
Project plan - Marketing

### ISSUE THREAD

**Issue by theodorosploumis** [theodorosploumis/drupal-docker-distros#3]
1. Add a Blog Post on my website
1. [x] Create a D.O. project
1. Share on D.O. lists/social
1. Create social announcements
1. Better Web UI (menu: about/usage/login, short video or animated gif)
1. Create Video to promote the project
1. Add Thumbnails for Distros on the list below (also, show as grid)
1. Better Ads/Sponsors
1. [x] Add share buttons
1. [x] Create GitHub releases
1. [x] Find a sponsor (sponsors banner)
1. [x] Add to [Drupaltools](https://drupaltools.github.io)
1. [x] Add Docker hub badges
1. [x] Add to Personal Portfolio
